name: Deploy GH Pages workflow

on:
  workflow_call:
    outputs:
      status:
        value: ${{ jobs.deploy.outputs.status }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    outputs:
      status: ${{ job.status }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'yarn'

      - name: Build static
        env:
          PUBLIC_APP_NAME: ${{ vars.PUBLIC_APP_NAME }}
          PUBLIC_APP_DOMAIN: ${{ vars.PUBLIC_APP_DOMAIN }}
          PUBLIC_APP_URL: ${{ vars.PUBLIC_APP_URL }}
          PRIVATE_PRICE_URL: ${{ secrets.PRIVATE_PRICE_URL }}
          PRIVATE_UNTAPPD_API_URL: ${{ secrets.PRIVATE_UNTAPPD_API_URL }}
          PRIVATE_UNTAPPD_CLIENT_ID: ${{ secrets.PRIVATE_UNTAPPD_CLIENT_ID }}
          PRIVATE_UNTAPPD_CLIENT_SECRET: ${{ secrets.PRIVATE_UNTAPPD_CLIENT_SECRET }}
          PRIVATE_UNTAPPD_ACCESS_TOKEN: ${{ secrets.PRIVATE_UNTAPPD_ACCESS_TOKEN }}

        run: |
          yarn
          yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
