name: Cron GH Pages workflow

on:
  schedule:
    - cron: '0 * * * *'
    #- cron: '*/20 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'yarn'

      - name: Build static
        env:
          PUBLIC_APP_NAME: ${{ vars.PUBLIC_APP_NAME }}
          PUBLIC_APP_DOMAIN: ${{ vars.PUBLIC_APP_DOMAIN }}
          PUBLIC_APP_URL: ${{ vars.PUBLIC_APP_URL }}
          PRIVATE_PRICE_URL: ${{ secrets.PRIVATE_PRICE_URL }}

        run: |
          yarn
          yarn build

  deploy:
    needs: build
    uses: 'Saturnych/actions-workflows/.github/workflows/pages-deploy.yml@develop'
    with:
      dir: 'distr'
    secrets: inherit

  email:
    needs: deploy
    uses: 'Saturnych/actions-workflows/.github/workflows/email.yml@develop'
    with:
      name: 'ohmybeer.ru build'
      status: ${{ needs.deploy.outputs.status }}
    secrets: inherit
