name: Develop GH Pages workflow

on:
  # Triggers the workflow on push events but only for the 'develop' branch
  push:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  playwright:
    uses: './.github/workflows/e2e-tests.yml'
    secrets: inherit

  deploy:
    uses: './.github/workflows/build-deploy.yml'
    secrets: inherit

  email:
    needs: deploy
    uses: 'Saturnych/actions-workflows/.github/workflows/email.yml@develop'
    with:
      name: 'ohmybeer.ru deploy'
      status: ${{ needs.deploy.outputs.status }}
    secrets: inherit
