name: Deploy GH Pages workflow

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
    outputs:
      status:
        value: ${{ jobs.deploy.outputs.status }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    outputs:
      status: ${{ job.status }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './${{ inputs.dir }}'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
